### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by sevenNightL** [fengyeju/microservice-solution#1]
你好，请问怎么联系你？

**Comment by fengyeju** [comment]
不提供其他联系方式，可以直接在这里贴出你的问题

**Comment by sevenNightL** [comment]
> 不提供其他联系方式，可以直接在这里贴出你的问题

是这样的，我把eshoponabp部署到了docker上面，但是本地访问不到，
这是我的hosts
<img width="800" alt="image" src="https://github.com/fengyeju/microservice-solution/assets/27542146/a2f30aa4-8933-44a8-a4a4-f6156caadc98">
这个是nginx配置
<img width="906" alt="image" src="https://github.com/fengyeju/microservice-solution/assets/27542146/3561c044-ff67-4945-ae37-8a22bd27eeb9">
目前eshoponabp的镜像已经打包到本地
<img width="1051" alt="image" src="https://github.com/fengyeju/microservice-solution/assets/27542146/9bd7c6de-25d1-4e9a-be64-62ffe29de3b9">
容器都启动了
<img width="980" alt="image" src="https://github.com/fengyeju/microservice-solution/assets/27542146/38232222-1465-4778-9a41-5fd818ee4616">
但是访问报错了，502
<img width="1018" alt="image" src="https://github.com/fengyeju/microservice-solution/assets/27542146/56980a2b-0150-4a34-bc02-603ae702449e">
请问这个怎么解决？我觉得这个可能信息量有点多，要是有联系方式的话，应该要方便查找问题一点。

**Comment by fengyeju** [comment]
每个运行的容器点进去看看有没有错误信息

**Comment by sevenNightL** [comment]
> 每个运行的容器点进去看看有没有错误信息

还真有

**Comment by sevenNightL** [comment]
> 每个运行的容器点进去看看有没有错误信息

还是不行，现在都没有错误了，但是还是502，容器里面也没有错误信息了

**Comment by fengyeju** [comment]
访问过之后再去看日志，会有的。另外容器里程序的运行目录下应该还有个logs目录，去里面找找错误提示

**Comment by sevenNightL** [comment]
> 访问过之后再去看日志，会有的。另外容器里程序的运行目录下应该还有个logs目录，去里面找找错误提示

没有，容器目录下的log日志没有错误。
这个配置没有错误吧。
<img width="670" alt="image" src="https://github.com/fengyeju/microservice-solution/assets/27542146/fd5f0a9f-aca2-44ca-8006-c7b2dfccf230">
我在本地浏览器访问http://eshop-st-public-web:80，应该访问的就是eshop-st-public-web这个容器吧？
<img width="735" alt="image" src="https://github.com/fengyeju/microservice-solution/assets/27542146/f13d54a6-9381-4daf-88b3-3d87fce1c989">

**Comment by sevenNightL** [comment]
> 访问过之后再去看日志，会有的。另外容器里程序的运行目录下应该还有个logs目录，去里面找找错误提示

是我nginx配置有问题吗？我直接默认请求localhost:80的话，会到一个项目的swagger里面去，如果
<img width="1084" alt="image" src="https://github.com/fengyeju/microservice-solution/assets/27542146/c54d08af-81ac-4930-bc56-b2a2558277fd">
请问这是什么原因呢？

**Comment by fengyeju** [comment]
看下这里的文档 https://github.com/abpframework/eShopOnAbp/blob/main/etc/README.md

**Comment by sevenNightL** [comment]
> 看下这里的文档 https://github.com/abpframework/eShopOnAbp/blob/main/etc/README.md

这个不是跑 k8s 的吗？我只是在 docker 里面跑

**Comment by fengyeju** [comment]
排查一下是不是ssl证书的问题

**Comment by sevenNightL** [comment]
> 排查一下是不是ssl证书的问题

这个是我生成的证书配置
<img width="858" alt="image" src="https://github.com/fengyeju/microservice-solution/assets/27542146/ec8429ec-b550-4d84-b699-d597b499fbaa">
这里有问题吗

**Comment by fengyeju** [comment]
看不出错误原因

**Comment by sevenNightL** [comment]
> 看不出错误原因

所有能联系一下你吗？帮我排查一下行吗，我找了很久不知道问题在哪里

**Comment by fengyeju** [comment]
如果每个容器直接能访问，那就是nginx的配置问题，具体怎么配置我也没研究过。
