### ISSUE TITLE
eshoponabp本地解析keycloak认证问题

### ISSUE THREAD

**Issue by sevenNightL** [fengyeju/microservice-solution#2]
当我的angular项目向docker上的keycloak认证的时候，如果我配置的是keycloak暴露的端口和ip时认证没有问题，如果我配置的是keycloak的本地解析时认证没反应了 angular项目地址是 [127.0.0.1:4200](http://127.0.0.1:4200/) keycloak的地址是 [127.0.0.1:8080](http://127.0.0.1:8080/) 我把keycloak本地解析为keycloak，但是认证没有反应。这是怎么回事? issues:https://github.com/abpframework/eShopOnAbp/issues/224

**Comment by fengyeju** [comment]
这和angular-oauth2-oidc的默认配置有关，见[AuthConfig.requireHttps](https://manfredsteyer.github.io/angular-oauth2-oidc/docs/classes/AuthConfig.html#requireHttps)

> Defines whether https is required. The default value is remoteOnly which only allows http for localhost, while every other domains need to be used with https.

**Comment by sevenNightL** [comment]
> 这和angular-oauth2-oidc的默认配置有关，见[AuthConfig.requireHttps](https://manfredsteyer.github.io/angular-oauth2-oidc/docs/classes/AuthConfig.html#requireHttps)
> 
> > Defines whether https is required. The default value is remoteOnly which only allows http for localhost, while every other domains need to be used with https.

好的，谢谢大佬

**Comment by sevenNightL** [comment]
> 这和angular-oauth2-oidc的默认配置有关，见[AuthConfig.requireHttps](https://manfredsteyer.github.io/angular-oauth2-oidc/docs/classes/AuthConfig.html#requireHttps)
> 
> > Defines whether https is required. The default value is remoteOnly which only allows http for localhost, while every other domains need to be used with https.

我已经改为了http
<img width="886" alt="image" src="https://github.com/fengyeju/microservice-solution/assets/27542146/a7128b33-2580-48ad-8933-5dc9ff0fbc9f">
为什么它还是https的请求？
<img width="1143" alt="image" src="https://github.com/fengyeju/microservice-solution/assets/27542146/cb5d5f42-d2bc-4dce-b87d-9cd4f0fd9b28">
而且它好像是http和https都请求了吗

**Comment by sevenNightL** [comment]
> > 这和angular-oauth2-oidc的默认配置有关，见[AuthConfig.requireHttps](https://manfredsteyer.github.io/angular-oauth2-oidc/docs/classes/AuthConfig.html#requireHttps)
> > > Defines whether https is required. The default value is remoteOnly which only allows http for localhost, while every other domains need to be used with https.
> 
> 我已经改为了http <img alt="image" width="886" src="https://private-user-images.githubusercontent.com/27542146/297068039-a7128b33-2580-48ad-8933-5dc9ff0fbc9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MTIzMDksIm5iZiI6MTcwNTQxMjAwOSwicGF0aCI6Ii8yNzU0MjE0Ni8yOTcwNjgwMzktYTcxMjhiMzMtMjU4MC00OGFkLTg5MzMtNWRjOWZmMGZiYzlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDEzMzMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3ZTQ3YjE0YTNiNWJkOTViN2FhNzYzYjRlZjM2NmM0ZGE4Y2ZjNGEyMGI3ZTE4YjNiMjdiOGIyYzQ3MDg5ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rI2kt-bwTQWG-xmwJbOJX7sLTS8tX9eeTy02kkV9Px0"> 为什么它还是https的请求？ <img alt="image" width="1143" src="https://private-user-images.githubusercontent.com/27542146/297068384-cb5d5f42-d2bc-4dce-b87d-9cd4f0fd9b28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MTIzMDksIm5iZiI6MTcwNTQxMjAwOSwicGF0aCI6Ii8yNzU0MjE0Ni8yOTcwNjgzODQtY2I1ZDVmNDItZDJiYy00ZGNlLWI4N2QtOWNkNGYwZmQ5YjI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDEzMzMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0YWI1MzkzMGE1NTA3MDRhOWE2ZDYwMTJkZDM2YmFlMDVjNmY3NGNkZTI0OTRjZDhhNjczOWM3N2M1NjNkYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yqC3mcLP4vNOGdOB_Sz4sgHR335Q5fw5oFoaiTciGhA"> 而且它好像是http和https都请求了吗

似乎还是走的http请求
<img width="1024" alt="image" src="https://github.com/fengyeju/microservice-solution/assets/27542146/b3ec8182-2329-427d-b6fa-fa6eb2cccae4">

**Comment by fengyeju** [comment]
这就不清楚了，如果只是本地访问，还是用localhost

**Comment by sevenNightL** [comment]
> 这就不清楚了，如果只是本地访问，还是用localhost

可以了，我代理影响了。
